name: dotup_dart_logger
description: Small library for logging.
version: 0.1.5
homepage: https://dotup.de
repository: https://github.com/dotupNET/dotup_dart_logger

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
