name: dotup_dart_logger
description: Small library for logging.
version: 0.3.3
homepage: https://dotup.de
repository: https://github.com/dotupNET/dotup_dart_logger

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter